
move_umi: True

programs:
    Duplicates: "markduplicates" #fgbio / markduplicates
    Trimming: "Fastp" #Cutadapt / Fastp / None
    markduplicate: "picard" #GPU / picard /picard_UMI

callers:
  list:
    - "mutect2"
    - "vardict"
    - "varscan"
    - "freebayes"
  sort_order: "mutect2,vardict,varscan,freebayes"

cnvkit:
  #extra: "--segment-method none"
  relevant_genes: "/apps/bio/repos/Twist_DNA/DATA/TSO500_relevant_genes.txt"

reference: #change to hg38
    ref: "/medstore/External_References/hg19/CHR/Homo_sapiens_sequence_hg19_CHR.fasta"
    dict: "/medstore/External_References/hg19/CHR/Homo_sapiens_sequence_hg19_CHR.dict"
    assembly: hg19
    chrom_len:
       chr1: 249250621
       chr2: 243199373
       chr3: 198022430
       chr4: 191154276
       chr5: 180915260
       chr6: 171115067
       chr7: 159138663
       chr8: 146364022
       chr9: 141213431
       chr10: 135534747
       chr11: 135006516
       chr12: 133851895
       chr13: 115169878
       chr14: 107349540
       chr15: 102531392
       chr16: 90354753
       chr17: 81195210
       chr18: 78077248
       chr19: 59128983
       chr20: 63025520
       chr21: 48129895
       chr22: 51304566
       chrX: 155270560
       chrY: 59373566

Background:
    background_panel: "/apps/bio/dependencies/twist_dna/Twist_DNA_pipeline/background_panel.tsv"

PoN:
    cnvkit: "/apps/bio/repos/Twist_DNA/DATA/cnvkit_Twist_PoN.cnn"
    #ONCOCNV: "DATA/ONCOCNV_Twist_PoN.txt"
    #ONCOCNV2: "DATA/ONCOCNV_Twist_PoN.Processed.txt"
    GATK: "/apps/bio/repos/Twist_DNA/DATA/GATK_Twist_PoN.hdf5"
    msisensor-pro: "/apps/bio/repos/Twist_DNA/DATA/Msisensor_pro_reference.list_baseline"

configfiles:
    multiqc: "/apps/bio/repos/Twist_DNA/Config/Pipeline/multiqc_config.yaml"
    vep: "/apps/bio/dependencies/twist_dna/Twist_DNA_pipeline/VEP/"

cnvkit:
    relevant_genes: "/apps/bio/repos/Twist_DNA/DATA/TSO500_relevant_genes.txt"

bed:
    bedfile: "/apps/bio/repos/Twist_DNA/DATA/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.bed" #Change to HG38 coordiantes
    intervals: "/apps/bio/repos/Twist_DNA/DATA/pool1_pool2_nochr_3c.sort.merged.padded20.hg19.210311.met.annotated.interval_list"
    GATK_CNV: "/apps/bio/repos/Twist_DNA/DATA/pool1_pool2_nochr_3c.sort.merged.hg19.210311.annotated.preprocessed.interval_list"
    GATK_CNV_SNPs: "/apps/bio/repos/Twist_DNA/DATA/gnomad_SNP_0.001_target.annotated.interval_list"

hotspot_combined: "/apps/bio/repos/Twist_DNA/DATA/Hotspots_combined.csv"

geneFuse:
    genes: "/apps/bio/repos/Twist_DNA/DATA/druggable.hg19.csv"

TMB:
    Artifacts: "/apps/bio/repos/Twist_DNA/DATA/Artifact_positions.txt"

mutect2:
    GetPileupSummaries: "/apps/bio/repos/Twist_DNA/DATA/chr17_small_exac_common_3.vcf.gz"

java:
    SOBDetector: "/apps/bio/dependencies/twist_dna/Twist_DNA_pipeline/SOBDetector_v1.0.1.jar"

singularity:
    default: "/apps/bio/dependencies/twist_dna/singularity/somatic-develop.simg" #"docker://gmsuppsala/somatic:develop"
    execute: "singularity exec -e -B /seqstore -B /medstore -B /apps --cleanenv " #"singularity exec -e -B /data -B /projects -B /scratch -B /data_twist_dna_cutadapt "
    gatk4_cnv: "/apps/bio/dependencies/twist_dna/singularity/gatk-4.1.9.0.simg" #"docker://broadinstitute/gatk:4.1.9.0"
    vep: "/apps/bio/dependencies/twist_dna/singularity/ensembl-vep-release_99.0.simg" #"docker://ensemblorg/ensembl-vep:release_99.0"

cartool:
    cov: "100 200 1000"

# FIX THIS!!
#samples: # path to samples.tsv 
#runfolder_path: # path to runfolder
#units: # path to units.tsv 
#samplesheet: #path to sample sheet 
bcl2fastq_version: 2.17.1.14
skip_chrs:
 - "MT"
